chore: add new movie
cued-up/movie_project pull request #2
Opened 2021-02-23 13:11 UTC by MoMonem

2021-02-23 13:55 UTC, cued-up requested changes
Thanks for adding a new movie. 

1. Please implement logging so that the user can see all of the movie changes.
2. Make ```movies``` into dictionary. 
3. We'll discuss on next meeting on how to commit to a local branch instead of master branch.

2021-02-23 13:55 UTC, cued-up reviewed
change into dict

2021-02-25 02:24 UTC, MoMonem commented
I just added the logging and did "git add ." then "git commit" and finally "git push" but I can't see any changes here in this thread, does that mean the commit I did is sent to you for approval or not yet? :D

2021-02-26 00:17 UTC, fcue requested changes

2021-02-26 00:17 UTC, fcue commented on movies.py
> +            logging.info('User inputted an invalid value.')
Nice work! Change this one to either warning or error since user is trying to input an invalid value :)

```suggestion
            logging.warning('User inputted an invalid value.')
```

2021-02-26 14:14 UTC, cued-up commented on movies.py
>          if movie['title'] == get_title:
removi for loop, replace with if else. 
```suggestion
    if get_title in movies['title']:
        print (f'{get_title} found.')
    else:
        print ('Not here')
```

2021-02-26 14:14 UTC, cued-up commented on movies.py
>      for movie in movies:
You can also remove for loop here if we are just displaying movies. 
```suggestion
    print (dict(zip(movies['title'], movies['year'])))
```

2021-02-26 14:14 UTC, cued-up commented on movies.py
>      for movie in movies:
And don't forget to add logging :)

2021-02-28 16:29 UTC, fcue approved these changes

2021-02-28 16:31 UTC, merged